# Generated by Django 5.2 on 2025-04-11 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3)),
                ('symbol', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Conversion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('from_cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_currency', to='quickstart.currency')),
                ('to_cur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_currency', to='quickstart.currency')),
            ],
        ),
    ]
